//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PathMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap education {
            get {
                object obj = ResourceManager.GetObject("education", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HLDTemplate.dot.
        /// </summary>
        internal static string HLDTemplateFileName {
            get {
                return ResourceManager.GetString("HLDTemplateFileName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap icn_align_shapes {
            get {
                object obj = ResourceManager.GetObject("icn_align_shapes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_autocorrect {
            get {
                object obj = ResourceManager.GetObject("icn_autocorrect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_bringforward {
            get {
                object obj = ResourceManager.GetObject("icn_bringforward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_bringtofront {
            get {
                object obj = ResourceManager.GetObject("icn_bringtofront", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_center_drawing {
            get {
                object obj = ResourceManager.GetObject("icn_center_drawing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_checkbox {
            get {
                object obj = ResourceManager.GetObject("icn_checkbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_color_palette {
            get {
                object obj = ResourceManager.GetObject("icn_color_palette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_connectortool {
            get {
                object obj = ResourceManager.GetObject("icn_connectortool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_connectshapes {
            get {
                object obj = ResourceManager.GetObject("icn_connectshapes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_copy {
            get {
                object obj = ResourceManager.GetObject("icn_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_corner_radius {
            get {
                object obj = ResourceManager.GetObject("icn_corner_radius", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_cut {
            get {
                object obj = ResourceManager.GetObject("icn_cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_dialog_state_count {
            get {
                object obj = ResourceManager.GetObject("icn_dialog_state_count", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_distributeshapes {
            get {
                object obj = ResourceManager.GetObject("icn_distributeshapes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_export {
            get {
                object obj = ResourceManager.GetObject("icn_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_file {
            get {
                object obj = ResourceManager.GetObject("icn_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_file_open {
            get {
                object obj = ResourceManager.GetObject("icn_file_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_fill {
            get {
                object obj = ResourceManager.GetObject("icn_fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_find {
            get {
                object obj = ResourceManager.GetObject("icn_find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_generate_ui {
            get {
                object obj = ResourceManager.GetObject("icn_generate_ui", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_generate_xml {
            get {
                object obj = ResourceManager.GetObject("icn_generate_xml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_glue_tool {
            get {
                object obj = ResourceManager.GetObject("icn_glue_tool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_import {
            get {
                object obj = ResourceManager.GetObject("icn_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_line {
            get {
                object obj = ResourceManager.GetObject("icn_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_new {
            get {
                object obj = ResourceManager.GetObject("icn_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_new_page {
            get {
                object obj = ResourceManager.GetObject("icn_new_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_paste {
            get {
                object obj = ResourceManager.GetObject("icn_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_pointer {
            get {
                object obj = ResourceManager.GetObject("icn_pointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_print {
            get {
                object obj = ResourceManager.GetObject("icn_print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_repeat {
            get {
                object obj = ResourceManager.GetObject("icn_repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_ruler {
            get {
                object obj = ResourceManager.GetObject("icn_ruler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_save {
            get {
                object obj = ResourceManager.GetObject("icn_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_sendbackward {
            get {
                object obj = ResourceManager.GetObject("icn_sendbackward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_sendtoback {
            get {
                object obj = ResourceManager.GetObject("icn_sendtoback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_shadow {
            get {
                object obj = ResourceManager.GetObject("icn_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_shapes_window {
            get {
                object obj = ResourceManager.GetObject("icn_shapes_window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_size_position {
            get {
                object obj = ResourceManager.GetObject("icn_size_position", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_snap_glue {
            get {
                object obj = ResourceManager.GetObject("icn_snap_glue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_spelling {
            get {
                object obj = ResourceManager.GetObject("icn_spelling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_stop {
            get {
                object obj = ResourceManager.GetObject("icn_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_text {
            get {
                object obj = ResourceManager.GetObject("icn_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icn_undo {
            get {
                object obj = ResourceManager.GetObject("icn_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice User Interface (*.vui)|*.vui|All Files (*.*)|*.*.
        /// </summary>
        internal static string OpenDialogFilter {
            get {
                return ResourceManager.GetString("OpenDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open VUI.
        /// </summary>
        internal static string OpenDialogTitle {
            get {
                return ResourceManager.GetString("OpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture (*.bmp; *.gif; *.jpg; *.png)|*.bmp;*.gif;*.jpg;*.png.
        /// </summary>
        internal static string OpenLogoDialogFilter {
            get {
                return ResourceManager.GetString("OpenLogoDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logo.
        /// </summary>
        internal static string OpenLogoDialogTitle {
            get {
                return ResourceManager.GetString("OpenLogoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel workbook (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string OpenPromptsFilter {
            get {
                return ResourceManager.GetString("OpenPromptsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Prompts.
        /// </summary>
        internal static string OpenPromptsTitle {
            get {
                return ResourceManager.GetString("OpenPromptsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui Document Changes (*.docx)|*.docx.
        /// </summary>
        internal static string OpenUISpecFilter {
            get {
                return ResourceManager.GetString("OpenUISpecFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Vui Document Changes.
        /// </summary>
        internal static string OpenUISpecTitle {
            get {
                return ResourceManager.GetString("OpenUISpecTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PathMakerLogo {
            get {
                object obj = ResourceManager.GetObject("PathMakerLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string PathMakerSchemaVersion {
            get {
                return ResourceManager.GetString("PathMakerSchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\PromptsToReview\.
        /// </summary>
        internal static string PromptRecordingLocation {
            get {
                return ResourceManager.GetString("PromptRecordingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to this drawing?.
        /// </summary>
        internal static string SaveAsPrompt {
            get {
                return ResourceManager.GetString("SaveAsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice User Interface (*.vui)|*.vui.
        /// </summary>
        internal static string SaveDialogFilter {
            get {
                return ResourceManager.GetString("SaveDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save VUI.
        /// </summary>
        internal static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastPath XML (*.xml)|*.xml.
        /// </summary>
        internal static string SaveFastPathXMLFilter {
            get {
                return ResourceManager.GetString("SaveFastPathXMLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export FastPath XML.
        /// </summary>
        internal static string SaveFastPathXMLTitle {
            get {
                return ResourceManager.GetString("SaveFastPathXMLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HLD Specification (*.docx)|*.docx.
        /// </summary>
        internal static string SaveHLDSpecFilter {
            get {
                return ResourceManager.GetString("SaveHLDSpecFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save High Level Design.
        /// </summary>
        internal static string SaveHLDSpecTitle {
            get {
                return ResourceManager.GetString("SaveHLDSpecTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to:.
        /// </summary>
        internal static string SavePrompt {
            get {
                return ResourceManager.GetString("SavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel workbook (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string SavePromptsFilter {
            get {
                return ResourceManager.GetString("SavePromptsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Prompts.
        /// </summary>
        internal static string SavePromptsTitle {
            get {
                return ResourceManager.GetString("SavePromptsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VUI Specification (*.docx)|*.docx.
        /// </summary>
        internal static string SaveUISpecFilter {
            get {
                return ResourceManager.GetString("SaveUISpecFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save UI Specification.
        /// </summary>
        internal static string SaveUISpecTitle {
            get {
                return ResourceManager.GetString("SaveUISpecTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VUITemplate.dot.
        /// </summary>
        internal static string VUITemplateFileName {
            get {
                return ResourceManager.GetString("VUITemplateFileName", resourceCulture);
            }
        }
    }
}
